version: "3.3"

services:
  publico:
    image: jenkins/jenkins:lts
    # container pode ser referenciado pelo nome
    container_name: jenkins
    # Mapeamento de porta entre host (esquerda) : container (direita)
    network_mode: host # necessário para utilizar o servidor de email do host
    # environment:
      # - JENKINS_OPTS="--prefix=/jenkins"
    # ports:
      # - 8080:8080
    #  - 50000:50000
    volumes:
      - /opt/jenkins:/var/jenkins_homes
      - /var/run/docker.sock:/var/run/docker.sock
      # Alinha o horário do container com o da máquina host
      - /etc/timezone:/etc/timezone
      - /etc/localtime:/etc/localtime
